### ISSUE TITLE
aspect ratio

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/dashboard#14]
Can we get the aspect ratio on the images for the frontends fixed?

**Comment by abrinckm** [comment]
Yes. This issue had been discussed during our dev meetings. 
I'm looking into this as a solution:
https://www.npmjs.com/package/ember-aspect-ratio-image

**Comment by ian-taylor** [comment]
I don’t think that this package will help.  The “image” class in the “ui card" that we’re using for the netflix style display already does this. The reason the aspect ratio has changed is because I enforced a specific height on the images so this overrides the default, which would maintain the aspect ratio. But the reason I added a fixed height is because the images that are there right now have different sizes so if we remove that, it looks really messy because each card has a different height, which defeats the purpose of the UI.

So, I would recommend the way to solve this would be as follows:

- resize all images that are used now so they use the same relative dimensions. 
- remove the fixed height from images - then the images and the aspect ratio will work ok
- create a image cropper utility upload image upload, which will allow the user to crop the image or fit the image into the space the way they want. We can then pad the image with whitespace or transparent background to make all images have the same aspect ratio

Thoughts?

**Comment by MatthewTurk** [comment]
I can't remember the specific magic that works, but in the past I've been able to specify one of the two (height or width) and used a `max-height` or `max-width` CSS attribute to allow it to get the aspect ratio right.  I don't think that either cropping or resizing is necessary, and it can be done just in CSS, but I could be wrong.

**Comment by ian-taylor** [comment]
We can try.  Maybe that’s what the ember aspect ratio tool that Adam mentioned does then? Adam, have a go with that and see what it does.

**Comment by ian-taylor** [comment]
I checked in CSS that should retain a max height of 140 px and maintain the aspect ratio.  It looks ok until the size of the browser is changed then the smooth responsive scaling is a compromised. Maybe this would work ok for a desktop/laptop. Try it out and see what you think.

**Comment by MatthewTurk** [comment]
Looks much better -- even though the DataONE logo is smaller, I like that they don't look squished anymore!  Thanks.  Unless you'd like to keep the ticket open, this looks good.  I don't think we need to bikeshed the sizes/centering at this time.
