### ISSUE TITLE
Registered data doesn't appear until refresh

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#180]
Dashboard `newui` build/commit 7199664.

Registering DOI `10.5065/D6862DM8`, I see the "Registering" notification, but the dataset doesn't appear in the view until I refresh.

**Comment by abrinckm** [comment]
As @ThomasThelen explained in #186, there is no upper bound we can use to determine when registration has finished. I think the best thing to do here is refresh every time we see a notification come through the stream. Thoughts?

**Comment by craig-willis** [comment]
This sounds like a reasonable solution to me for the short term.  Ideally we can later implement what @ThomasThelen described by retrieving the initial list.

**Comment by ThomasThelen** [comment]
We can probably get the refresh down to a single time by checking the content of the notification. This would probably be checking against a string, like

if msg == 'Registration Complete'
{
   refreshPage()
}

I think the notification stream is the official way to get information from the backend; I wonder if there's a way to make a channel specifically for background things that the user doesn't need to know about. That way we can check for status codes rather than checking against message strings.

**Comment by abrinckm** [comment]
short term solution implemented in commit [c35d23a](https://github.com/whole-tale/dashboard/commit/c35d23adb0f4e48a2f38883f7c4d6b1134ad102b)
