### ISSUE TITLE
Can't compose tale using data from existing tale

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#182]
Based on discussion with Kacper:

In the old dashboard, the user could compose a tale using data from another tale. On the Home page, they could select from the "Catalog" to copy data to their workspace. From the Compose > Data page, they could "select from registered datasets."  This was functionality in the original design that seems to have been lost in the redesign.   This may be part of "Indexing, remixing of the frontends (1.2.3)", which is now part of release 0.7

**Comment by abrinckm** [comment]
I need clarification on this issue. 

It was requested to remove Workspace folder in #194. I believe users should copy data into their Data folder instead? or the Home folder. 

About the registered datasets:  @Xarthisius I can add registered datasets using GET /datasets, correct?

**Comment by Xarthisius** [comment]
Yes, you can use `GET /datasets`. User should be able to copy folders/files from the list of datasets to their own Data (we do that e.g. during registration). However there's no way to currently do that in the dashboard since we don't list it anywhere. We used to have a separate widget and each dataset had "copy to Home" button AFAIR.

I think with current UI, it would be ideal to plug it into File chooser widget (right bottom) in the 'compose' view as third, top-level root folder (maybe name it "Datasets"? I'm sure there's going to be a lengthy naming discussion with this one...). Since that widget operates on "Folders" and "Items", it may be more convenient to access Datasets via it's folder root: `GET /resource/lookup` with param `path=%2Fcollection%2FWholeTale%20Catalog%2FWholeTale%20Catalog`

**Comment by abrinckm** [comment]
Okay. sounds good to me!

**Comment by Xarthisius** [comment]
Fixed by adding ability to copy a Tale.
