### ISSUE TITLE
Double menu

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#183]
In the dev environment, we currently display 2 upper menus:

<img width="589" alt="screen shot 2018-07-02 at 2 18 56 pm" src="https://user-images.githubusercontent.com/4334350/42182150-eca66560-7e02-11e8-9ac3-8fb6fbd2ea11.png">

One menu is from wholetale.org, the other from the dashboard.  We discussed two options:
* Short term (for exec call):  Remove upper menu (About, Team, Participate) and move Run, Compose, Manage to upper menu. 
* Longer term (for MVP release) Merge wholetale.org and dashboard.wholetale.org into a single application (single menu, put static content in dashboard container)

**Comment by ian-taylor** [comment]
Please note, that the UI mockups that were agreed include this double menu:

https://github.com/whole-tale/wt-design-docs/blob/master/_static/dashboard-clickable-files/images/wholetale-rethink_3-Manage.jpg

Damien has removed this for the exec call but that second menu was intentional as per mockup.  I don't think merging these is the way to go as it'll lose the clean design of the app. I would suggest either we stick to the two menus as per agreed design or we include a single link in the footer to WholeTale.org for more information.

**Comment by Xarthisius** [comment]
@ian-taylor that was the consensus we reached during last call: we're gonna remove it now since it's not working and would confuse potential users, but once we're ready to add actual content for those tabs, they'll be brought back.

**Comment by ian-taylor** [comment]
@xarthisius - ok, thanks, that makes perfect sense. But let's not try and combine them.
