### ISSUE TITLE
Responsive styling issues

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#184]
Using the Chrome developer console responsive view suggests a number of potential general styling issues:

<img width="430" alt="screen shot 2018-07-02 at 2 50 16 pm" src="https://user-images.githubusercontent.com/4334350/42183398-4ae241b8-7e07-11e8-8014-4705664e7040.png">

dashboard:newui build/commit 7199664

**Comment by ian-taylor** [comment]
Thanks Damien for having a try at this.  Craig, all, given the consolidated view concept we should probably have a few more UI sessions to look at these and decide a strategy for mobile phones. Obviously the consolidated view is not appropriate for mobile phones so we may need to redesign the app for mobile phone use.  However, I am not sure what is promised in the proposal here and the effort we want to put into this.

**Comment by Xarthisius** [comment]
This bug was merely related to scaling issues for top navbar and footer. We had similar issues with  presenting the dashboard using projector. The responsive console was used as the easiest way to reproduce the issue. We were not trying to suggest supporting mobile devices. That's certainly out of scope for MVP.

TBH, I personally don't see the need for supporting small screens at all.

**Comment by craig-willis** [comment]
Ran through all pages with resolution 1024x768 and everything looks good to me.  Thanks @cyberdante.

**Comment by craig-willis** [comment]
Footer and space between panel and footer is a little odd on Safari. I assume we want to support Safari?

![screen shot 2018-07-10 at 10 36 15 am](https://user-images.githubusercontent.com/4334350/42520926-223e875e-842d-11e8-9e5e-06e42337435c.png)
