### ISSUE TITLE
Dashboard allows user to create same tale multiple times

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#200]
Trying to confirm @kylechard's problem with 12 copies of the same tale, we found that it is possible to click the `Launch New Tale` button multiple times, creating multiple separate tales.

To repeat:
* https://dashboard.stage.wholetale.org/compose
* Input title, select environment
* Select "Launch New Tale" repeatedly and rapidly

You will have multiple instances of the same tale. Perhaps we can disable the "Launch" button on click?

**Comment by ThomasThelen** [comment]
The quickest fix for this is to probably disable the button after they've clicked it. It could probably be bullet-proofed by checking if there is already a tale creation job running.

**Comment by abrinckm** [comment]
possibly resolved in commit [08b6118](https://github.com/whole-tale/dashboard/commit/08b6118e1085c3afb9c00a139ce7fed447d02454)

**Comment by abrinckm** [comment]
@craig-willis @kylechard I had a very hard time to replicate this bug locally because of how fast I transition into the tale view after clicking on "Launch New Tale". I barely have a split second to click the button again. However, I was after trying able to create 3 tales in a row. And I have implemented a safe guard as suggested by @ThomasThelen. I am unable to replicate locally, but perhaps the best test is to deploy to dev and test.

**Comment by craig-willis** [comment]
I can no longer click the button multiple times in succession.

**Comment by ThomasThelen** [comment]
Just tested on 08b6118 and can confirm the page change and button disabling works nicely!
