### ISSUE TITLE
Do not allow "Move To" Home from Data folder

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#201]
As noted by @kylechard, moving data from the Data directory to Home does not work. This is currently not supported by the `wt_home_dirs` plugin.  For MVP, remove "Home" from the Move To options in the Data folder.  Users should still be able to move within the Data folder.

**Comment by abrinckm** [comment]
@craig-willis can users move items & folders from Home into Data? or should this be disallowed as well?

**Comment by craig-willis** [comment]
Good question, I'll need @Xarthisius to confirm.  My understanding is that Data contains now only registered data,  therefore users should not be allowed to move from Home to Data.

**Comment by Xarthisius** [comment]
`Home -> Data` works, but since the Tale composer widget allows to freely select files from Home, there's no gain in explicitly enabling that functionality for `Manage` view. Furthermore, it may not be obvious to the user what that operation actually entails (making a snapshot).
Bottom line: let's disable it for now.

**Comment by abrinckm** [comment]
fixed in commit [1f4d8f1](https://github.com/whole-tale/dashboard/commit/1f4d8f128354515ebac4167a9532b903e140c828)

okay, you can no longer move files from home to data or from data to home

**Comment by craig-willis** [comment]
Indeed, I can't. This works for me.
