### ISSUE TITLE
Can't upload large files

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#228]
See also https://app.zenhub.com/workspace/o/whole-tale/terraform_deployment/issues/34 and 
https://wholetale.slack.com/archives/G3QBV6QDC/p1532098658000352

Confirming Niall's report that I can't upload large files (e.g., 200MB).

Dev console reports
```
https://girder.stage.wholetale.org/api/v1/file/chunk

  "field": "id",
    "message": "Invalid ObjectId: chunk",
    "type": "validation"
```
with error `net::ERR_FAILED`

It looks like the UI is uploading the full file, without chunking.
https://github.com/whole-tale/girder/blob/master/clients/web/src/models/FileModel.js#L225

We are able to upload large files via Girder Web ui directly, but it is chunking the file into sub 100Mb chunks.

**Comment by swyngaard** [comment]
This should now be resolved in commit [a0d5c40](https://github.com/whole-tale/dashboard/commit/a0d5c4074b6bd471cb8899d9871d15c4bd49e58e). Essentially we needed to upgrade to a later version of DropzoneJS because the older version did not support chunking. You will need to perform an `npm install` and restart the dashboard instance before changes take effect.

Files larger than 100MB are now uploaded in 10MB chunks. I'm not sure what the optimal chunk size would be at this point but we can easily adjust this value.

Please test and let me know if there is anything I may have missed.

**Comment by craig-willis** [comment]
I think even 1GB would be fine for now.  Probably more important is indicating to the user that there is a limit:  "Not uploaded: file exceeds upload limits of 1GB" or similar.

**Comment by swyngaard** [comment]
I adjusted the maximum file size to 1GB and tested that it can successfully upload such a large file:
![1gb_upload_success](https://user-images.githubusercontent.com/14008086/44364312-a1b66380-a494-11e8-81ba-3975449a56a7.png)
Additionally, if you exceed the maximum file size a more useful error message is displayed in the interface:
![1 1gb_upload_failure](https://user-images.githubusercontent.com/14008086/44364401-e8a45900-a494-11e8-8f2d-5a263a76675a.png)
Please test and let me know if you get expected results.
P.S. If you happen to be using Linux, the `fallocate` tool is a quick and convenient way to create large files.

**Comment by abrinckm** [comment]
i need to remember fallocate. that is useful
