### ISSUE TITLE
Update External Data tab to use new Tale model

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#355]
PR https://github.com/whole-tale/girder_wholetale/pull/213 changes the Tale model, allowing involatileData to be edited independently of the session.  The External Data tab currently references the `dataSet` obtained from `dm/session` and should be change to the `dataSet` in the Tale object `involatileData`.

Completion criteria:
* [x] Update External Data tab to use Tale endpoint
* [x] Confirm ability to add/remove data from external data (relates to and may depend on fixes to #352 #353 #354 )

**Comment by bodom0015** [comment]
Looking into this... for clarity, was this the External Data tab on the "Run" page? Or was this a temporary fix for the "Manage" page?

Sorry that I'm having such trouble keeping track

**Comment by craig-willis** [comment]
Yeah, it's confusing for sure.  This issue refers to "Run > External Data".

If helpfule:
* Manage > Data:  This allows users to register external data into the system and today displays a list of all of the data you have registered. This will eventually become [Data Catalog > My External Data](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse-catalog.html) based on mockups.
* Run > External Data: This allows users to select specific external data to be associated with a Tale.

**Comment by bodom0015** [comment]
Ah, that is quite helpful.. thank you, Craig!

So I did notice an oddity: https://github.com/whole-tale/dashboard/blob/master/app/components/ui/tale-tab-files/component.js#L243

I think this is the clause I'd need to change, which would need to read dataset ids from the `/user`, instead of reading them from `/dm/session`. Assuming that the dataset format hasn't changed terribly, this shouldn't be difficult.

The oddity: Notice that line 243 and line 258 are the same... if that's the case, then the clause under line 258 will never be hit and can be likely removed. If my assessment is correct, should I remove this code?

**Comment by craig-willis** [comment]
That's right -- moving from `/dm/session` to `/tale`.  They should be using the same format.

The duplicate code may be the result of a merge error after rebasing the earlier PRs.  I don't know which block is correct, and they are subtly different -- maybe explaining one of the bugs? Regardless, I trust that you'll make the right decision on which to remove.
