### ISSUE TITLE
Registered data does not show up in 'Imported data'

### ISSUE THREAD

**Issue by mbjones** [whole-tale/dashboard#38]
Registered data does not show up in 'Imported data' list on home page.  I clicked the 'Add' button, searched for and found the DataONE dataset 'urn:uuid:3249ada0-afe3-4dd6-875e-0f7928a4c171', and the a notification popped up saying that data were registered, but then the data do not show up in the imported data list.  I checked both the first and last page of the Imported data list.  I also reloaded the page, and the data do not show up in the list.

Browser: Chrome Version 58.0.3029.110 (64-bit)
OS: Mac OS Sierra (10.12.4)

**Comment by abrinckm** [comment]
The notification for this particular dataset did in fact show 'error'. However, it isn't obvious since the notification is very quick and easy to miss. And the second notification (after failing) did not show 'error' at all. So it appears to the user that it was meant to succeed. 
So I'll make and link this to another issue #41. 

To address the actual error:
This particular dataset cannot be harvested because of an error within the XML loaded from this URL:
<https://cn.dataone.org/cn/v2/resolve/urn%3Auuid%3A1dced450-d07f-42e9-8c47-58724c75412b>

The exact error message is: `rdf:nodeID value is not a valid NCName: _:6b0f92aa-9449-48a9-af06-c83dbb5436d5'`

I'm not sure what is wrong with that node because I'm not familiar with those XMLs.

**Comment by mbjones** [comment]
Thanks, @abrinckm -- that error you encountered is indeed a [validation error in our ORE resource map document](https://github.com/ropensci/datapack/issues/79) -- we'll have to get it fixed.  But in the meantime, I think the WholeTale UI needs to be more explicit that a dataset could not be imported when something goes awry -- I totally missed the error message.

**Comment by Xarthisius** [comment]
@abrinckm do we need a better error handling on the backend or is it something to be handled on the frontend?

**Comment by bodom0015** [comment]
Appears to have been resolved in #41
