### ISSUE TITLE
File Location Links Missing Middle Paths in Run > Files

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/dashboard#425]
When navigating into folders, you can only navigate back to the root (Home, Workspace, etc)

To Reproduce:
1. Launch a Tale
2. Navigate to Run > Files
3. Create a series of nested folders
4. Navigate into the folders and attempt to navigate one directory back

Demo At http://g.recordit.co/j8jV7BX57Q.gif

**Comment by bodom0015** [comment]
After much investigation, it would appear that the missing bread-crumbs here are actually by design. See https://github.com/whole-tale/dashboard/blob/master/app/components/ui/files/bread-crumbs/template.hbs#L4-L35

The `justDescription` flag on the `bread-crumbs` component seems to toggles behavior that will list off the full breadcrumb:
* `true` => do not list full breadcrumb
* `false` => list full breadcrumb

Unfortunately, this is currently mutually-exclusive with the `displayFolderMenu` boolean, which we almost certainly need in the Run view.

Shifting this logic around a bit, I should be able to adjust the `justDescription` case to include a full bread-crumb, if this might be desirable
