### ISSUE TITLE
Implement "Create Tale" modal

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#452]
Per the [mockups](http://www.crc.nd.edu/~kfurse/wholetale-css-mock-up-sui_f2018/browse.html), the "Compose" panel will be re-implemented as the "Create Tale" modal. This will require the following:

* Implementing the "Create Tale" modal
* Adding "Create New Tale" button. This can go on the Browse page for now until Browse is refactored.
* Removing the "Compose" panel

Note, the mockups don't factor in the "Analyze in WT" integration that prepopulates the form based on query string parameters, for example:

https://dashboard.stage.wholetale.org/compose?environment=RStudio+%28rocker%2Fgeospatial%29&name=Satellite+Telemetry+Dataset+%28Raw%29%3A+Juvenile+Bearded+and+Spotted+Seals%2C+2004-2006%2C+Kotzebue%2C+Alaska.&uri=10.24431%2Frw1k118

This will also need to be supported.

**Comment by abrinckm** [comment]
![Select Data button](https://user-images.githubusercontent.com/8681111/55957870-5fb17c00-5c35-11e9-9fab-6eb7163e82cc.png)

Hi, 
Does anyone know what this button does? Does this open the select data modal?

**Comment by abrinckm** [comment]
@craig-willis 
A couple of quick questions:

1. Do you want this button disabled and grayed out when a tale is being created?
2. What functionality do you expect when a user navigates to the compose link you copy pasted? Should that link read `/browse?[query params]` instead? And should this automatically trigger the "Create Tale" modal to open up with prepopulated values?

Thanks

**Comment by abrinckm** [comment]
@craig-willis Another question:
The compose panel not only creates a tale but also automatically launches the tale. 
Do you want this modal to do the same?

**Comment by Xarthisius** [comment]
1. No, it should be active. It's grayed out right now in the compose view, because there were some problems related to the code. As for the latter I think temporarily we should navigate to the browse view. The old Tale view is going away, the new Tale view is still being implemented (https://github.com/whole-tale/dashboard/pull/459).
2. I'll start with an easier part of the question: `/browse?` sounds ok and it should automatically trigger the "Create Tale" modal. The rest is tricky. Data referenced via query params may not yet be registered in the system, so there's no id that can be used in "select data". The form in this case also uses a different API endpoint to create a Tale (`POST /tale/import` rather than plain `POST /tale`). Response for this POST is a Job rather than a Tale, which is used to show progress. It's really a completely different path... Right now it looks like that:

![analyze](https://user-images.githubusercontent.com/352673/56368121-68b5c680-61bc-11e9-9937-731da0d0bfb1.png)

It's just a prepopulated text entry.

**Comment by Xarthisius** [comment]
> @craig-willis Another question:
> The compose panel not only creates a tale but also automatically launches the tale.
> Do you want this modal to do the same?

If you don't mind the scope creep, I'd kill for a dropdown button with a default action (it can still be "Launch New Tale" by default). You know the same kind e.g. GitHub has for merge button:

![button](https://user-images.githubusercontent.com/352673/56369200-7ff5b380-61be-11e9-9342-8654afaa4d10.png)

**Comment by abrinckm** [comment]
@craig-willis @Xarthisius I have question about tracking progress. Currently, there is a tale import progress tracker on the compose panel. Do you want this to be put on the browse panel? Since we are deleting compose panel? It made sense on the compose panel but it doesn't make sense on the browse page. Not sure what do you guys think?

**Comment by abrinckm** [comment]
I think that even if you wanted to implement some kind of progress tracker on the browse panel that should be a separate issue.

**Comment by Xarthisius** [comment]
I'd say this should go to the UI notification stream handler as a toast, but let's defer the answer to that for when UI/UX group reconvenes
