### ISSUE TITLE
Dashboard external data integration (GUI to interact with harvesting API)

### ISSUE THREAD

**Issue by abrinckm** [whole-tale/dashboard#5]
Craft a GUI that leverages the [harvester API](https://girder.wholetale.org/api/v1#/harvester).

**Comment by Xarthisius** [comment]
https://github.com/whole-tale/girder_ythub/commit/674491cd99d42d0c3d51d47a1a7262a31e6a8ce0 is deployed. You can activate `register` button and use it to pass `dataMap` to `POST /folder/register`.

**Comment by Xarthisius** [comment]
Suggestions from @mbjones:
 * if only one data set is found, it would be best to select it automatically, rather than making the user pick it from the dropdown
 * it's not clear when the search is done - I had to guess to look in the dropdown — it would be good if the dropdown showed some content when a search was successful, like maybe going from disabled to enabled, and changing the default text from blank to ‘Select one of the data sets found…'
 * it would be fairly easy to support substring matches in the DataONE SOLR implementation by adding wildcards to the search strings provided

**Comment by abrinckm** [comment]
These two issues are done after commit [16a241c](https://github.com/whole-tale/dashboard/commit/16a241c60ebca2620d5d0802d95a3479de8115c4)
- if only one data set is found, it would be best to select it automatically, rather than making the user pick it from the dropdown
- it's not clear when the search is done ...

**Comment by abrinckm** [comment]
@mbjones @Xarthisius 
Regarding suggestion: "it would be fairly easy to support substring matches in the DataONE SOLR",
I need some more information about this...

What I'm doing is attempting to query DataONE through the Girder API using wildcards like this:
`/register/lookup?dataId=["10.5063/F1Z899C*"]`
I expect that it would return at least the dataset `10.5063/F1Z899CZ` but instead returns `no object was found`.

**Comment by mbjones** [comment]
Maybe add a wildcard on the front of your search string too, as I think its missing the "doi:" up front, so maybe your call would be:
```/register/lookup?dataId=["*10.5063/F1Z899C*"]```
Does that work?

**Comment by abrinckm** [comment]
Sorry I didn't close the loop on wildcards issue. Kacper informed me in slack chat that he is using regex to extract the doi from the string and ignores asterisks. He made a separate issue for it yesterday.

**Comment by Xarthisius** [comment]
This one is done, regex got a separate issue: https://github.com/whole-tale/girder_ythub/issues/5
