### ISSUE TITLE
Analyze dataset "as a tale"

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#503]
[Needs UI/UX input]

PR https://github.com/whole-tale/girder_wholetale/pull/317 adds the capability to optionally treat a registered dataset as a tale, importing contents into the workspace instead of as a registered datasets.  The use case is as follows: a researcher publishes a Binder-compatible (non-Tale) package to a supported repository (e.g., Dataverse, DataONE). Another user wants to review/re-run the published package in Whole Tale, treating the package contents as the workspace instead of a read-only dataset.  

A prototype UI implementation was created for the Dataverse community meeting (https://github.com/whole-tale/dashboard/tree/dv_fun), adding a toggle to the compose page to allow the user to import "as Tale" instead of as registered data.

**Comment by bodom0015** [comment]
For clarity, hidden support for the `asTale` option was added to the `create-tale-modal` in #548.

This ticket would be adding an explicit UI option that will default to the initial state of `asTale` and allow the user to toggle it as well, instead of relying purely on the query string parameter to set the value in the API call for us.

Ideally we should be able to use something simple out of the box, as we already have a range of different styles of checkboxes, toggles, and sliders at our disposal: https://semantic-ui.com/modules/checkbox.html

**Comment by ThomasThelen** [comment]
I think this was done in https://github.com/whole-tale/dashboard/pull/580
