### ISSUE TITLE
Handling invalid environment during AiWT

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#585]
This is minor, but I had a mismatch in the environment name ("Jupyter Lab" v "JupyterLab") between the stage and local environments and noticed during testing that a helpful error message is swallowed by the error handler:

https://dashboard.local.wholetale.org/browse?uri=https%3A%2F%2Fdoi.org%2F10.5281%2Fzenodo.1215988&name=weecology%2FPortalData&environment=XXX

<img width="902" alt="Screen Shot 2020-01-21 at 12 50 16 PM" src="https://user-images.githubusercontent.com/4334350/72919317-446fb300-3d15-11ea-99cd-daa4ecf7b88b.png">

The actual error in this case is "Could not find specified environment: XXX"

I also noticed that the "Create" button is disabled in this case.  

Possible solutions:
* Display underlying error message, since we know the cause
* In the event of a bad environment, let the user proceed with environment selection.

**Comment by ThomasThelen** [comment]
It looks like the issue is [handleError](https://github.com/whole-tale/dashboard/blob/master/app/components/ui/create-tale-modal/component.js#L163). If it gets an error with a `responsJSON` field it will set the error message to `responseJSON.message`. If it gets a generic exception (which has e.message) it will use the default error message, "There was an error while creating your Tale".

I think this is to gobble up any nasty stack traces that the system gives and instead give a nice message to the user. In our case, [we create an exception](https://github.com/whole-tale/dashboard/blob/master/app/components/ui/create-tale-modal/component.js#L104) that looks identical to the ones we're trying to gobble up.

If we're fine with setting the error message without using `handleError`, which may be counter-style I have a branch [here](https://github.com/whole-tale/dashboard/compare/missing_env_error) that I can turn into a PR.
