### ISSUE TITLE
Tale images not shown on browse page

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/dashboard#604]
We removed https://github.com/whole-tale/dashboard/pull/599 from rc2 because of an apparent side-effect related to displaying the tale images on the browse page.

I'm seeing this on my dev instance now on master. If I click "My Tales" the image displays:

<img width="1366" alt="Screen Shot 2020-02-28 at 9 12 38 AM" src="https://user-images.githubusercontent.com/4334350/75555574-81148580-5a0a-11ea-8dc7-3802c81754c9.png">

**Comment by bodom0015** [comment]
**Steps to Reproduce**
1. Clear `localStorage` manually or close all incognito windows and open a fresh incognito window
2. Navigate to Browse

**Expected Results**
List of Tales should be displayed with their images

**Actual Results**
No Tale images are displayed, even though all Tales are still listed here

**Root Cause**
We aren't properly setting the `filter` value when no saved value is detected in `localStorage`

PR incoming
